version: '3'
services:
  db1:
    image: mysql:latest
    ports:
      -  "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - sql_mode=''

  tenant1:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - sql_mode=''

  tenant2:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - sql_mode='' 
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db1
      - tenant2
      - tenant1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: manager
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 8080:8080