FROM maven:3.9.6-sapmachine-21 AS build
COPY . /home/app

RUN mvn -f /home/app/pom.xml clean package -DskipTests


FROM openjdk:21
COPY --from=build /home/app/target/multi-tenant-0.0.1-SNAPSHOT.jar /usr/local/lib/multi-tenant.jar
CMD ["java", "-jar", "/usr/local/lib/multi-tenant.jar"]